Update ammonite.json to point at new Main
In https://github.com/com-lihaoyi/Ammonite/pull/1229, the main method was renamed. Running the most recent version of ammonite gives:

```
Error: Main method not found in class ammonite.Main, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```

This can be worked around locally by running:
`cs launch ammonite -M ammonite.AmmoniteMain -- yourScript.sc`